name: Main pipeline

on:
  - push

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit --version
      - name: Run pre-commit
        run: |
          pre-commit run --all-files --verbose --color always

  build-site:
    name: Build and test site
    runs-on: ubuntu-latest
    needs: pre-commit
    env:
      MKDOCS_VERSION: 1.*
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install MkDocs
        run: |
          pip install "mkdocs==${MKDOCS_VERSION}"
          mkdocs --version
      - name: Build site
        run: |
          mkdocs build --clean --strict
      - name: Test site
        run: |
          test -f ./site/404.html
          test -f ./site/index.html
          test -f ./site/search/search_index.json
          grep -q 'Welcome to MkDocs' ./site/index.html
