name: CI/CD

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  debug:
    name: Run debug steps
    runs-on: ubuntu-latest
    container:
      image: alpine:3.10
    steps:
      - uses: actions/checkout@v1
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: |
          echo "$STEPS_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "$JOB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
          echo "$RUNNER_CONTEXT"

  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pre-commit
        run: |
          python --version
          pip --version
          pip install pre-commit
          pre-commit --version
      - name: Run pre-commit
        run: |
          pre-commit run --all-files --verbose --color always

  build-site:
    name: Build site
    runs-on: ubuntu-latest
    container:
      image: flaudisio/mkdocs:1
    needs: pre-commit
    steps:
      - uses: actions/checkout@v1
      - name: Build site
        run: |
          mkdocs --version
          mkdocs build --clean --strict
      - name: Upload site artifacts
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: site/

  test-site:
    name: Test site
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - uses: actions/checkout@v1
      - name: Download site artifacts
        uses: actions/download-artifact@v1
        with:
          name: site
      - name: Test site
        run: |
          test -f ./site/404.html
          test -f ./site/index.html
          test -f ./site/search/search_index.json
          grep -q 'Welcome to MkDocs' ./site/index.html

  publish-site:
    name: Publish site
    runs-on: ubuntu-latest
    container:
      image: flaudisio/awscli:1
    needs: test-site
    if: github.ref == 'master'
    env:
      BUCKET_NAME: tolentinof-github-actions-tests
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Download site artifacts
        uses: actions/download-artifact@v1
        with:
          name: site
      - name: Run S3 sync
        run: |
          aws --version
          aws s3 sync --delete ./site s3://$BUCKET_NAME
