name: Main pipeline

on:
  - push

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    container:
      image: flaudisio/pre-commit:latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          pre-commit --version
          pre-commit run --all-files --verbose --color always

  build-site:
    name: Build site
    runs-on: ubuntu-latest
    needs: pre-commit
    env:
      MKDOCS_VERSION: 1.*
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install MkDocs
        run: |
          pip install "mkdocs==${MKDOCS_VERSION}"
          mkdocs --version
      - name: Build site
        run: |
          mkdocs build --clean --strict
      - name: Upload site artifacts
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: site/

  test-site:
    name: Test site
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - uses: actions/checkout@v1
      - name: Download site artifacts
        uses: actions/download-artifact@v1
        with:
          name: site
      - name: Test site
        run: |
          test -f ./site/404.html
          test -f ./site/index.html
          test -f ./site/search/search_index.json
          grep -q 'Welcome to MkDocs' ./site/index.html
