name: Main pipeline

on:
  - pull_request
  - push

jobs:
  pre-commit:
    name: Run pre-commit steps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit --version
      - name: Run pre-commit
        run: |
          pre-commit run --all-files --verbose
